-- MySQL Script generated by MySQL Workbench
-- 02/20/16 19:38:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema surgery_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `surgery_database` ;

-- -----------------------------------------------------
-- Schema surgery_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `surgery_database` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `surgery_database` ;

-- -----------------------------------------------------
-- Table `surgery_database`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`patient` (
  `Pssn` INT NOT NULL COMMENT '',
  `Fname` VARCHAR(45) NOT NULL COMMENT '',
  `Lname` VARCHAR(45) NOT NULL COMMENT '',
  `Age` INT NOT NULL COMMENT '',
  `Sex` VARCHAR(45) NOT NULL COMMENT '',
  `Nationality` VARCHAR(45) NOT NULL COMMENT '',
  `Visit date` DATE NOT NULL COMMENT '',
  `Departure date` DATE NOT NULL COMMENT '',
  `Bill` INT NOT NULL COMMENT '',
  `Phone` INT NOT NULL COMMENT '',
  `Address` VARCHAR(75) NOT NULL COMMENT '',
  PRIMARY KEY (`Pssn`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`Engineer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`Engineer` (
  `Essn` INT NOT NULL COMMENT '',
  `Fname` VARCHAR(45) NOT NULL COMMENT '',
  `Lname` VARCHAR(45) NOT NULL COMMENT '',
  `Age` INT NOT NULL COMMENT '',
  `Sex` VARCHAR(45) NOT NULL COMMENT '',
  `Nationality` VARCHAR(45) NOT NULL COMMENT '',
  `Qualification` VARCHAR(45) NOT NULL COMMENT '',
  `Salary` INT NOT NULL COMMENT '',
  `Address` VARCHAR(45) NOT NULL COMMENT '',
  `Phone` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Essn`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`Doctor` (
  `Dssn` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fname` VARCHAR(45) NOT NULL COMMENT '',
  `Lname` VARCHAR(45) NOT NULL COMMENT '',
  `Age` INT NOT NULL COMMENT '',
  `Sex` VARCHAR(45) NOT NULL COMMENT '',
  `Nationality` VARCHAR(45) NOT NULL COMMENT '',
  `Specialty` VARCHAR(45) NOT NULL COMMENT '',
  `Salary` INT NOT NULL COMMENT '',
  `Address` VARCHAR(45) NOT NULL COMMENT '',
  `Phone` INT NOT NULL COMMENT '',
  `Work hours` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Dssn`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`Nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`Nurse` (
  `Nssn` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fname` VARCHAR(45) NOT NULL COMMENT '',
  `Lname` VARCHAR(45) NOT NULL COMMENT '',
  `Age` INT NOT NULL COMMENT '',
  `Sex` VARCHAR(45) NOT NULL COMMENT '',
  `Salary` INT NOT NULL COMMENT '',
  `Nationality` VARCHAR(45) NOT NULL COMMENT '',
  `Address` VARCHAR(45) NOT NULL COMMENT '',
  `Phone` INT NOT NULL COMMENT '',
  `work hours` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Nssn`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`OR's`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`OR's` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Operation type` VARCHAR(75) NOT NULL COMMENT '',
  `Start hour` TIME(45) NOT NULL COMMENT '',
  `Finish hour` TIME(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`Devices` (
  `Code` INT NOT NULL COMMENT '',
  `Dname` VARCHAR(45) NULL COMMENT '',
  `Model` VARCHAR(45) NULL COMMENT '',
  `Engineer_Essn1` INT NOT NULL COMMENT '',
  `OR's_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Code`)  COMMENT '',
  INDEX `fk_Devices_Engineer2_idx` (`Engineer_Essn1` ASC)  COMMENT '',
  INDEX `fk_Devices_OR's1_idx` (`OR's_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_Devices_Engineer2`
    FOREIGN KEY (`Engineer_Essn1`)
    REFERENCES `surgery_database`.`Engineer` (`Essn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Devices_OR's1`
    FOREIGN KEY (`OR's_ID`)
    REFERENCES `surgery_database`.`OR's` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`Dependent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`Dependent` (
  `Doctor_Dssn` INT NOT NULL COMMENT '',
  `Nurse_Nssn` INT NOT NULL COMMENT '',
  `Shift Hours` INT NULL COMMENT '',
  PRIMARY KEY (`Doctor_Dssn`, `Nurse_Nssn`)  COMMENT '',
  INDEX `fk_Doctor_has_Nurse_Nurse1_idx` (`Nurse_Nssn` ASC)  COMMENT '',
  INDEX `fk_Doctor_has_Nurse_Doctor1_idx` (`Doctor_Dssn` ASC)  COMMENT '',
  CONSTRAINT `fk_Doctor_has_Nurse_Doctor1`
    FOREIGN KEY (`Doctor_Dssn`)
    REFERENCES `surgery_database`.`Doctor` (`Dssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Nurse_Nurse1`
    FOREIGN KEY (`Nurse_Nssn`)
    REFERENCES `surgery_database`.`Nurse` (`Nssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`OR Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`OR Booking` (
  `Doctor_Dssn` INT NOT NULL COMMENT '',
  `OR's_ID` INT NOT NULL COMMENT '',
  `Booking rate` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Doctor_Dssn`, `OR's_ID`)  COMMENT '',
  INDEX `fk_Doctor_has_OR's_OR's1_idx` (`OR's_ID` ASC)  COMMENT '',
  INDEX `fk_Doctor_has_OR's_Doctor1_idx` (`Doctor_Dssn` ASC)  COMMENT '',
  CONSTRAINT `fk_Doctor_has_OR's_Doctor1`
    FOREIGN KEY (`Doctor_Dssn`)
    REFERENCES `surgery_database`.`Doctor` (`Dssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_OR's_OR's1`
    FOREIGN KEY (`OR's_ID`)
    REFERENCES `surgery_database`.`OR's` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`Dr.Pt.Relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`Dr.Pt.Relationship` (
  `patient_Pssn` INT NOT NULL COMMENT '',
  `Doctor_Dssn` INT NOT NULL COMMENT '',
  PRIMARY KEY (`patient_Pssn`, `Doctor_Dssn`)  COMMENT '',
  INDEX `fk_patient_has_Doctor_Doctor1_idx` (`Doctor_Dssn` ASC)  COMMENT '',
  INDEX `fk_patient_has_Doctor_patient1_idx` (`patient_Pssn` ASC)  COMMENT '',
  CONSTRAINT `fk_patient_has_Doctor_patient1`
    FOREIGN KEY (`patient_Pssn`)
    REFERENCES `surgery_database`.`patient` (`Pssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_has_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_Dssn`)
    REFERENCES `surgery_database`.`Doctor` (`Dssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `surgery_database`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`category` (
  `category_id`  NOT NULL COMMENT '',
  `name` (255) NOT NULL COMMENT '',
  PRIMARY KEY (`category_id`)  COMMENT '');

USE `surgery_database` ;

-- -----------------------------------------------------
-- Placeholder table for view `surgery_database`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surgery_database`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `surgery_database`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `surgery_database`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `surgery_database`.`view1`;
USE `surgery_database`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
